
version: 2.1

jobs:

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["b8:82:94:33:76:53:d5:96:08:a3:a3:f6:c5:22:42:72"]
          name: "Install dependencies"
          command: |
            apk add --update ansible
      - run:
          name: "Configure server"
          command: |
            cd ansible
            ansible-playbook main.yml -i inventory.txt

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - configure_infrastructure
